# Generated by Django 4.2.21 on 2025-08-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_alter_contest_private_contestants_and_more'),
        ('judge', '0151_contestparticipation_has_exited_and_more'),
    ]

    operations = [
    ]
