# Generated by Django 4.2.23 on 2025-09-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0153_alter_profile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name for identification', max_length=200)),
                ('subject', models.CharField(help_text='Email subject (overrides template if custom)', max_length=500)),
                ('body', models.TextField(help_text='Email body (overrides template if custom)')),
                ('is_html', models.BooleanField(default=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='bulk_email_files/')),
                ('email_column', models.CharField(default='email', help_text='Column name containing email addresses', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('partially_sent', 'Partially Sent')], default='draft', max_length=20)),
                ('total_emails', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, help_text='Error details if campaign failed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Email Campaign',
                'verbose_name_plural': 'Bulk Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the template', max_length=200, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('body', models.TextField(help_text='Email body content (HTML and plain text supported)')),
                ('is_html', models.BooleanField(default=True, help_text='Whether the body contains HTML content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('template_test', 'Template Test'), ('bulk_campaign', 'Bulk Campaign'), ('individual', 'Individual Email')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.bulkemailcampaign')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkemailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.emailtemplate'),
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid', 'Invalid Email')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data from uploaded file for personalization')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='judge.bulkemailcampaign')),
            ],
            options={
                'verbose_name': 'Email Recipient',
                'verbose_name_plural': 'Email Recipients',
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
