# Generated by Django 4.2.23 on 2025-09-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_bulkemailcampaign_emailtemplate_emaillog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkemailcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': '📧 Send Bulk Emails', 'verbose_name_plural': 'Bulk emailing'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': '📋 Email Log', 'verbose_name_plural': '📋 Logs (Complete History)'},
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'verbose_name': '📧 Email Recipient', 'verbose_name_plural': '📊 Recipients (Individual Status)'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-updated_at'], 'verbose_name': '📝 Email Template', 'verbose_name_plural': '📝 Templates (Reusable Emails)'},
        ),
    ]
