# Generated by Django 4.2.25 on 2025-10-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_problem_problem_type_mcqoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_type',
        ),
        migrations.AlterField(
            model_name='mcqoption',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='judge.mcqproblem'),
        ),
    ]
