# Generated by Django 4.2.25 on 2025-10-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_mcqproblem_remove_problem_problem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('code', 'Programming Problem'), ('mcq', 'Multiple Choice Question')], default='code', max_length=10),
        ),
    ]
