# Generated by Django 4.2.25 on 2025-10-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_problem_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('code', 'Coding Problem'), ('mcq', 'MCQ Problem')], default='code', max_length=10),
        ),
    ]
