# Generated by Django 4.2.25 on 2025-10-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('code', 'Programming'), ('mcq', 'Multiple Choice')], default='code', help_text='Determines whether this is a coding or MCQ problem.', max_length=10, verbose_name='problem type'),
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='judge.problem')),
            ],
        ),
    ]
