# Generated by Django 4.2.25 on 2025-11-16 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0157_alter_profile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSubmission',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('source', models.TextField(null=True)),
                ('username', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'judge_latestsubmission',
            },
        ),
    ]
