# Generated by Django 4.2.25 on 2025-11-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_latestsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSubmissionPG',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('contest_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('source', models.TextField(null=True)),
                ('username', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'latest_submissions_pg',
                'managed': False,
            },
        ),
    ]
