# Generated by Django 4.2.25 on 2025-11-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_latestsubmissionpg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='latestsubmission',
            table='latest_submissions',
        ),
        migrations.AlterModelTable(
            name='latestsubmissionpg',
            table='latest_submissions',
        ),
    ]
