# Generated by Django 4.2.25 on 2025-11-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_alter_latestsubmission_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='latestsubmission',
            table='latest_submissionsMB',
        ),
    ]
