# Generated by Django 4.2.25 on 2025-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0162_mcqresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='mcq_problems',
            field=models.ManyToManyField(blank=True, help_text='Multiple-choice questions included in this contest.', related_name='contests', to='judge.mcqproblem', verbose_name='MCQ Problems'),
        ),
    ]
