# Generated by Django 4.2.23 on 2025-12-10 19:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0163_remove_mcqquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='randomization_config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='Configuration for random problem selection.', verbose_name='randomization configuration'),
        ),
        migrations.AddField(
            model_name='contest',
            name='randomize',
            field=models.BooleanField(default=False, help_text='Randomly assign problems to users from the selected pool.', verbose_name='randomize problems'),
        ),
    ]
