# Generated by Django 4.2.23 on 2025-12-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0165_remove_mcq_name_types_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMCQSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0.0, verbose_name='points earned')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', related_query_name='contest_submission', to='judge.contestmcq', verbose_name='contest MCQ')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_mcq_submissions', related_query_name='contest_mcq_submission', to='judge.contestparticipation', verbose_name='participation')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry', to='judge.mcqsubmission', verbose_name='MCQ submission')),
            ],
            options={
                'verbose_name': 'contest MCQ submission',
                'verbose_name_plural': 'contest MCQ submissions',
                'unique_together': {('mcq', 'participation')},
            },
        ),
    ]
