# Generated by Django 4.2.23 on 2025-12-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0166_add_contest_mcq_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqsubmission',
            name='contest_object',
            field=models.ForeignKey(blank=True, help_text='Contest this submission belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to='judge.contest', verbose_name='contest'),
        ),
    ]
