# Generated by Django 4.2.23 on 2025-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0167_alter_mcqsubmission_contest_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='mcq_score',
            field=models.FloatField(default=0, help_text='Total score from MCQ questions only.', verbose_name='MCQ score'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='problem_score',
            field=models.FloatField(default=0, help_text='Total score from coding problems only.', verbose_name='problem score'),
        ),
    ]
