# Generated by Django 4.2.23 on 2025-12-21 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0168_add_problem_mcq_score_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the URL after /problem/', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Problem code must be ^[a-z0-9-]+$ (lowercase letters, numbers, and hyphens)')], verbose_name='problem code'),
        ),
    ]
