# Generated by Django 4.2.23 on 2025-12-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0169_allow_hyphens_in_problem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Difficulty level: Easy, Medium, or Hard', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.problemgroup', verbose_name='difficulty'),
        ),
    ]
