# Generated by Django 4.2.23 on 2025-12-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0170_add_difficulty_group_to_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='The type/category of question (e.g., Arrays, Graphs, etc.)', to='judge.problemtype', verbose_name='question types'),
        ),
    ]
