# Generated by Django 4.2.27 on 2026-01-14 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0171_add_types_to_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the URL after /problem/', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Problem code must be ^[a-z0-9-]+$ (lowercase letters, numbers, and hyphens)')], verbose_name='problem code'),
        ),
    ]
